#Name:         Eric Paulz
#Instructor:   Brygg Ullmer
#Class:          3220
#Date:           11-12-2018

make: main.cpp cscbitmap.cpp
	g++ main.cpp cscbitmap.cpp -pthread

run:
	./a.out lena512.bmp 20

clean:
	rm a.out 1.bmp
